### ISSUE TITLE
Installation problem - version requirement

### ISSUE THREAD

**Issue by sawula** [Calysto/skulpt_python#3]
Hi,

Trying to install the skulpt-kernel using 
`pip install --upgrade skulpt-kernel`
Getting the error message
`Could not find a version that satisfies the requirement skulpt-kernel (from versions: ).  No matching distribution found for skulpt-kernel.`

I'm on 
- Windows 8.1 Enterprise
- Notebook server 4.1.0
- Python 2.7.11
- Anaconda 2.5.0 (64-bit)

I believe I already have Metakernel, and Calysto installed via `pip`.

Thanks in advance.  I'm new to changing kernels on IPython notebooks.  Can't problem-solve well at this point.

**Comment by blink1073** [comment]
Hi @p5k12, it looks like the README instructions are wrong, can you try `pip install skulpt_python`?

**Comment by sawula** [comment]
Thanks.  I get a different error:
`Collecting skulpt-python`
`Using cached skulpt_python-0.9.2.tar.gz`
`Complete output from command python setut.py egg_info:`
`Traceback (most recent call last):`
`File "<string>", line 1, in <module>`
`File "c:\users\msawula\appdata\local\temp\pip-build-imznya\skulpt-python\setup.py",`
`line 49, in <module>`
`with open('README.md') as f:`
`IOError: [Errno 2] No such file or directory: 'README.md'`

**Comment by blink1073** [comment]
It looks like @dsblank will have to make a new release after merging #4.  In the mean time you can:

```
git clone https://github.com/Calysto/skulpt_python
cd skulpt_python
python setup.py install
```

**Comment by dsblank** [comment]
New release made; thanks @blink1073 and @p5k12 !

Also includes the updated config to use Processing.

**Comment by sawula** [comment]
thanks! it works!
